import { motion } from 'motion/react';
import { AnalysisResult } from '../types';
import { Share2, Download, ArrowLeft } from 'lucide-react';
import { DesktopDashboard } from '../components/DesktopDashboard';
import { MobileDashboard } from '../components/MobileDashboard';
import { useParams, useNavigate } from 'react-router-dom';

interface ResultsScreenProps {
  history: AnalysisResult[];
}

export const ResultsScreen = ({ history }: ResultsScreenProps) => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  
  const result = history.find(h => h.timestamp.toString() === id);

  if (!result) {
    return (
      <div className="flex flex-col items-center justify-center p-20 text-center space-y-6">
        <h2 className="font-headline text-3xl font-bold text-white">Diagnostic Not Found</h2>
        <p className="text-on-surface-variant">The requested log does not exist or has been removed.</p>
        <button onClick={() => navigate('/dashboard/diagnostics')} className="px-6 py-3 bg-primary text-black font-bold rounded-full">
          Return to Diagnostics
        </button>
      </div>
    );
  }

  const handleShare = async () => {
    const shareData = {
      title: `Crop Diagnosis: ${result.disease_name}`,
      text: `AgriNova AI Diagnosis\nCrop: ${result.disease_name}\nRisk: ${result.risk_level.toUpperCase()}\nAdvice: ${result.contextual_insight}`,
      url: window.location.href,
    };
    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(`${shareData.text}\nView at: ${shareData.url}`);
        alert("Report summary copied to clipboard!");
      }
    } catch (err) {
      console.error("Share failed", err);
    }
  };

  const handleDownload = () => {
    const report = `
# AgriNova AI - Agricultural Intelligence Report
Generated: ${new Date(result.timestamp).toLocaleString()}

## Diagnosis: ${result.disease_name}
Status: ${result.status.toUpperCase()}
Confidence Score: ${Math.round(result.confidence_score * 100)}%
Risk Level: ${result.risk_level.toUpperCase()}

## Contextual Insight
${result.contextual_insight}

## Treatment Plan
${result.treatment_steps.map((s, i) => `${i + 1}. ${s.title}: ${s.description}`).join('\n')}

## Preventive Measures
${result.preventive_measures.map((s, i) => `- ${s}`).join('\n')}

---
Generated by AgriNova AI
    `.trim();

    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AgriNova_Report_${result.disease_name.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <div className="flex items-center justify-between mb-8">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-on-surface-variant hover:text-white transition-colors">
          <ArrowLeft className="w-5 h-5" />
          <span className="font-bold">Back</span>
        </button>
        <div className="flex space-x-2">
          <button onClick={handleShare} className="bg-surface-container border border-white/10 p-3 rounded-2xl hover:bg-white/10 transition-all text-white" title="Share Report">
            <Share2 className="w-5 h-5" />
          </button>
          <button onClick={handleDownload} className="bg-surface-container border border-white/10 p-3 rounded-2xl hover:bg-white/10 transition-all text-white" title="Download Offline Copy">
            <Download className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="hidden md:block">
        <DesktopDashboard result={result} />
      </div>

      <div className="block md:hidden">
        <MobileDashboard result={result} />
      </div>
    </motion.div>
  );
};
